insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Fixflex', 'Boilermaker', 32, 45);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Cookley', 'Welder', 14, 16);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Wrapsafe', 'Carpenter', 28, 8);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Alphazap', 'Carpenter', 35, 42);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Asoka', 'Tile Setter', 25, 45);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Tampflex', 'Laborer', 39, 86);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Regrant', 'Safety Officer', 8, 95);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Home Ing', 'Glazier', 13, 21);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Daltfresh', 'Equipment Operator', 29, 66);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Sonsing', 'Plumber', 13, 65);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Zaam-Dox', 'Pipefitter', 8, 44);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Hatity', 'Pipefitter', 9, 35);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Daltfresh', 'Carpenter', 1, 72);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Zaam-Dox', 'Plumber', 23, 74);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Sub-Ex', 'Tile Setter', 4, 22);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Fix San', 'Brickmason', 7, 27);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Veribet', 'Safety Officer', 40, 68);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Home Ing', 'Pipelayer', 23, 15);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Home Ing', 'Waterproofer', 11, 71);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Aerified', 'Carpenter', 25, 5);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Lotstring', 'Tile Setter', 26, 70);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Namfix', 'Ironworker', 1, 53);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Aerified', 'Sheet Metal Worker', 25, 34);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Aerified', 'Tile Setter', 24, 67);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Konklux', 'Landscaper', 33, 87);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Lotlux', 'Ironworker', 26, 11);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Quo Lux', 'Brickmason', 5, 88);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Sub-Ex', 'Stucco Mason', 17, 96);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Subin', 'Linemen', 35, 62);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Ventosanzap', 'Stucco Mason', 20, 55);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Flowdesk', 'Stucco Mason', 29, 79);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Fintone', 'Pipefitter', 39, 15);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Redhold', 'Welder', 37, 80);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Cookley', 'Linemen', 33, 49);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Stim', 'Welder', 37, 33);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Flowdesk', 'Tile Setter', 40, 95);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Cardify', 'Tile Setter', 11, 84);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('It', 'Pipefitter', 34, 93);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Job', 'Equipment Operator', 20, 55);
insert into subjects (subject_name, subjects_description, speciality_id, subject_teacher_id) values ('Alphazap', 'Linemen', 8, 60);